### ISSUE TITLE
SIgnaturePad - Change Clear Button Text

### ISSUE THREAD

**Issue by sk1llsh0t** [FreakyAli/Maui.FreakyControls#93]
### Description

I'm trying to change the clear button text from a "X" to "Clear". I created a png image called "clear.png" and got the base64 encoded string of the image. setting the ClearImageBase64 property to this string doesn't change the button image. How can I do this?

Thanks!

**Comment by sk1llsh0t** [comment]
I realized my error. I was using a png and not a svg. after converting the png to svg and then base64 encoding the image, it started working.

**Comment by FreakyAli** [comment]
@sk1llsh0t  Happy to know you found a solution to your issue, if you find the repo resourceful be sure to share it with your friends and leave a ⭐ that keeps me going, Also feel free to leave a feature or control request if any 😄

**Comment by sk1llsh0t** [comment]
I was able to update the clear button text but it is quite tiny. is there a way to change the size of the button on the control?

**Comment by FreakyAli** [comment]
Well the thing is I designed it in a way that it was supposed to be an icon, and hence I gave it a fixed size of 35 which you can find 
https://github.com/FreakyAli/Maui.FreakyControls/blob/756d7f0c78e41df4756a01b06d033b557cdb44a7/MAUI.FreakyControls/MAUI.FreakyControls/Shared/FreakySignatureView/FreakySignaturePadView.xaml#L32

Now there are two things that can be done, either you can create your own version of SignaturePad using the `FreakySignatureCanvasView` and then you can edit it as you like or you can raise a PR with the option to customize size. 

If you want me to add this feature, I can but it won't happen soon since I have some other controls in mind that are on priority and I need those for my personal projects. 

I would recommend you create your own SignaturePad using SignatureCanvas that way you will have full control over the design of it!
